### ISSUE TITLE
Clarify `required`/`default` values for the `base_branch` input

### ISSUE THREAD

**Issue by nobe4** [GrantBirki/git-diff-action#8]
Hi 👋 

The [README](https://github.com/GrantBirki/git-diff-action/blob/4f9cae84434d5c38df243272c02135493f01ef5c/README.md) states that the `base_branch` input is both `required` with a `default` value:

https://github.com/GrantBirki/git-diff-action/blob/4f9cae84434d5c38df243272c02135493f01ef5c/README.md?plain=1#L178-L180

The `action.yaml` has a similar config: 

https://github.com/GrantBirki/git-diff-action/blob/4f9cae84434d5c38df243272c02135493f01ef5c/action.yml#L5-L8

Unless I've misread [the doc](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputsinput_idrequired), it seems that those two shouldn't be used together.

In this case, I'd say that making it **optional** is the way to go: in PR, we usually want to diff the code against the base branch, which is the default you've defined.

**Comment by GrantBirki** [comment]
I think it is _okay_ to use both the `required` and `default` values in the `action.yml` file but perhaps I'm miss interpreting it myself...

The way I read it is that the `base_branch` input is required otherwise the workflow will fail. The user can either pass in their own value, or leave it blank and the `default` value will be used. So if a user wants to alter the `base_branch` behavior they can by overwriting this value. Or they can leave it blank and its value will be automatically set. Either way, a _value_ is required one way or another.

**Comment by nobe4** [comment]
I agree that the doc leaves some room for interpretation.
The way I read, it makes those two mutually exclusive (but it's definitely not, given that the workflows work).

Either way, it should probably be an update in the github docs instead of here.
